name: CD

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  push-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=tag
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{version}}

      - name: start production deployment
        uses: bobheadxi/deployments@v1
        id: production-deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production
          ref: ${{ github.head_ref }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Dokploy Deployment
        env:
          DOKPLOY_URL: ${{ secrets.DOKPLOY_URL }}
          DOKPLOY_AUTH_TOKEN: ${{ secrets.DOKPLOY_AUTH_TOKEN }}
          DOKPLOY_APPLICATION_ID: ${{ secrets.DOKPLOY_PROD_APPLICATION_ID }}
        run: |
          response=$(curl -X 'POST' \
            "$DOKPLOY_URL/api/application.deploy" \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -H "Authorization: Bearer $DOKPLOY_AUTH_TOKEN" \
            -H "x-api-key: $DOKPLOY_AUTH_TOKEN" \
            -d "{\"applicationId\": \"$DOKPLOY_APPLICATION_ID\"}" \
            -w "%{http_code}" \
            -o /dev/null \
            -s)

          if [ "$response" -ne 200 ]; then
            echo "Deployment failed with status code: $response"
            exit 1
          fi

      - name: update deployment status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          env: ${{ steps.production-deployment.outputs.env }}
          deployment_id: ${{ steps.production-deployment.outputs.deployment_id }}
          ref: ${{ github.head_ref }}
          env_url: ${{ secrets.PROD_APP_URL }}

  create-release:
    # https://github.com/marketplace/actions/create-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.ref_name }}
          makeLatest: true
          generateReleaseNotes: true
